### ISSUE TITLE
AGB-E02-20 missing materials for C1-C3

### ISSUE THREAD

**Issue by andreevgy** [HDR/NintendoPCBs#10]
Hello!

I am kinda new to hobby electronics and trying to fix AGB-E02-20 that I bought secondhand. I successfully transferred chips and elements that I had on previous board, but from photos online it seems like I have С1-С3 missing.

In the BOM of AGB-E02-20 there is no C1-C3. Maybe they shouldn't be here and I just screwed my cartridge, but I see all other boards mention it. Will appreciate any help and thank you for the designs!

**Comment by HDR** [comment]
C1-C3 are 0.1uF (100nF) 0402 capacitors, i've updated the BOM to reflect this
