### ISSUE TITLE
Assembled AGB-E02-20 Board

### ISSUE THREAD

**Issue by emuman100** [HDR/NintendoPCBs#2]
I had the board made with a thickness of .8mm at OSH Park. For the LE26FV10NITS-10 save flash, the pad spacing is just large enough and it had to be very carefully aligned and was a bit difficult to flow solder since the pads were not pretinned, but ENIG plated. 

I soldered the save flash, mask ROM, and capacitors of Super Mario Advance 4 and it did not boot. The mask ROM is AX4E-0. Have you tested this design?

**Comment by HDR** [comment]
Yep, works as it should.

**Comment by emuman100** [comment]
Ok, maybe something happened to this masked ROM. It was a working cartridge, then just stopped working. Usually the masked ROMs are pretty reliable. I'll just have to try with another donor cartridge. Picture attached. 
![AGB cart PCB](https://user-images.githubusercontent.com/64179229/80052612-14d57000-84e9-11ea-9f1b-9502aa649e9d.jpeg)

**Comment by emuman100** [comment]
It won't even read in my insidegadgets programmer. I believe it is the mask ROM.
