### ISSUE TITLE
how to build Dookie ?

### ISSUE THREAD

**Issue by hpx1984** [HDR/NintendoPCBs#3]
Hi Sir HDR

The Ique dookie project is the clones of ique card,right?

i had download Dookie Gerber and Sch but can't open it by CAM350 and Protel99, what PC tool can open it?

the process how to clones ique card in my understand,am i right?
1.dump original NAND from original ique card 
2.build Dookie PCBA
3. upload original NAND file to Dookie PCBA

**Comment by hpx1984** [comment]
CAM350 can open AGB-E05-01 but Dookie gerber showed as below
![image](https://user-images.githubusercontent.com/76941051/158632179-ab35047c-d05c-4335-873f-632efa1f266d.png)

**Comment by HDR** [comment]
i'm not sure what you're trying to do, but the gerber file can be used at any fab, these boards are only meant as replacement boards and require donor parts from a real board.

**Comment by hpx1984** [comment]
hi HDR
thanks your replayed 

i used CAM350 for open DOOKIE gerber always got error as this or just sew the "Drl" layer 
i thinking about for rebuild a ique card for lager memory for install all 14 ique player games in one ique card
and i think DOOKIE project is what i want when i saw this project , i like to try to build it 
![image](https://user-images.githubusercontent.com/76941051/158738968-5aaf13c7-c25d-47a3-be59-99786da5a4ff.png)

**Comment by HDR** [comment]
Your software is broken, you need to upload the gerber to a fab.

**Comment by hpx1984** [comment]
Dear MrHDR 

i got ique memory card DOOKIE PCB now 
and i try for soldering a nand chip and cap on it but i can't programmed nand bin file on it by used ique player hot swap memory card and use ique_diag tool 
is it mean need nand programmer for read nand file from original memory card's nand chip then programming nand file to new nand chip by programmer?

sorry for trouble you and many thanks your kindly help 
  
![image](https://user-images.githubusercontent.com/76941051/161371232-9fa492a0-0bb1-4015-b04f-dcc20a14f748.png)
![image](https://user-images.githubusercontent.com/76941051/161371233-b1254ffa-f11c-4c32-8117-5d7ff37153ea.png)

**Comment by HDR** [comment]
Not sure, i haven't tried using them myself, i just cloned the board.

**Comment by hpx1984** [comment]
okay ,let me try myself , many thanks your replied Mr HDR
thank you very much
