### ISSUE TITLE
DMG-KFDN-01 - C4, C5 missing connection to ground.

### ISSUE THREAD

**Issue by mkarr** [HDR/NintendoPCBs#4]
Hi,

It appears that in both the schematic and pcb for the DMG-KFDN-01 project, C4 and C5 are connected together, but that connecting net is not connected to ground. 

Looking over the PCB pictures here:

https://gbhwdb.gekkio.fi/cartridges/DMG-APAU-0/mattcurrie-1.html

It appears that the ground connection is there, similar MBC3 boards appear to have the same connections for the SRAM.

Thanks,

Mike

**Comment by HDR** [comment]
Whoops, when i originally made some of those i was kind of a newbie when it came to pcb's, i just pushed d1a9a5f which should fix this.
