### ISSUE TITLE
Question - Is there a reason some pads are many pads connected to each other?

### ISSUE THREAD

**Issue by sabogalc** [HDR/NintendoPCBs#8]
In this example, I am looking at the pads of `U1` on the `AGB-E02-20` PCB. I am wondering if there is any particular reason that the pads are all three pads strung together instead of one pad. I am looking to submit a PR that corrects this, but before I do so I wanted to check if this was the intended design.
![Screenshot 2024-03-27 173033](https://github.com/HDR/NintendoPCBs/assets/53708281/77349a97-e745-41f9-b825-099f000638a2)
![Screenshot 2024-03-27 175650](https://github.com/HDR/NintendoPCBs/assets/53708281/d2326b84-a19e-471e-98c8-21395553878e)

**Comment by HDR** [comment]
This is intentional, please look at an original board or the 3d view.
